#!/bin/bash
./run_waitingplan_2-dial.sh
./run_waitingplan_2-dial.sh
./run_waitingplan_2-dial.sh
./run_waitingplan_2-dial.sh
./run_waitingplan_2-dial.sh
./run_waitingplan_2-dial.sh
./run_waitingplan_2-dial.sh
./run_waitingplan_2-dial.sh
./run_waitingplan_2-dial.sh
./run_waitingplan_2-dial.sh
